# Network Binding (Prevents conflict with systemd-resolved)
bind-interfaces
listen-address=10.20.30.1
port=0

interface=eth2

# DHCP Server (Assigns IP and Boot File)
dhcp-range=10.20.30.100,10.20.30.200,255.255.255.0,12h
dhcp-boot=pxelinux.0,,10.20.30.1

# TFTP Server (REQUIRED for file transfer which is mentioned on setup-pxe.sh)

# used for debugging
log-dhcp
